version: '3'
services:
  redis:
    image: redis:6
    container_name: redis
    hostname: redis
    privileged: true
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./data:/data
    command: [ "redis-server", "/etc/redis/redis.conf"]
